### ISSUE TITLE
Figure out the future of multiple generic x86_64 images

### ISSUE THREAD

**Issue by mtoman** [balena-os/balena-generic#21]
At this moment we have two "generic intel" types, one of them is `genericx86-64-ext` from `balena-intel` and the other one is `generic-amd64` from this repo. Though similar there are differences between them:
- Kernel configuration
-  `genericx86-64-ext` supports both BIOS and UEFI boot while `generic-amd64` only supports UEFI
-  `genericx86-64-ext` builds a flasher while  `generic-amd64` builds a flat image
- Naming is not very descriptive for either of the two (the NUC being called `genericx86-64` adds even more to this)

We need to discuss this and decide how to approach this, the two obvious ways are:
- Keep both and improve docs/naming
- Replace one by another in a transparent way

**Comment by jakogut** [comment]
> Kernel configuration

I think  we should build a fairly generic kernel, suitable for a wide range of hardware, like distros do.

> genericx86-64-ext supports both BIOS and UEFI boot while generic-amd64 only supports UEFI

BIOS/MBR booting is basically obsolete. UEFI has had widespread support in PCs and servers since at least 2008. Even if someone *does* have hardware lying around that's that old, a Raspberry Pi 4 would be more practical and capable. Maybe it's worth discussing dropping support for BIOS/MBR?

> genericx86-64-ext builds a flasher while generic-amd64 builds a flat image

Maybe it's worth building both in this repository?

**Comment by kb2ma** [comment]
My confusion on this topic as a docker-compose file creator led me to this issue. Thanks for the clear summary. Without understanding the internal complexities, I think a single image named 'generic-amd64' would make the compose file creator's task much simpler.

**Comment by mtoman** [comment]
The `balena-intel` counterpart: https://github.com/balena-os/balena-intel/issues/374

**Comment by alexgg** [comment]
This was discussed in an arch call https://jel.ly.fish/a3972594-b0c7-4fcb-8b05-e3836536cb95 and I am writing an improvement with the conclusions.

**Comment by alexgg** [comment]
This is now begin tracked as an improvement.
